### ISSUE TITLE
Problem with  harvesting plants

### ISSUE THREAD

**Issue by Palbosa** [War3zuk/War3zuk-Alpha-18-Stable-AIO#3]
Hi, it seems there is a problem with the plants and harvesting.

Even with "Living off the land" maxed out, I can only harvest 1 per grown plant.

And as the seeds cost 5 to craft, it's impossible to maintain a garden. 

Shouldn't normally the seeds cost 2 or 3, and harvesting 5 or 6 so that way you can grow a garden?

**Comment by War3zuk** [comment]
Yeah gonna sort out the vanilla recipe today

**Comment by Palbosa** [comment]
Hello, I see that you made the upgrade ! 

Thanks very much, this will make having a garden way easier ! 

I really like the modpack you made, one of the bests! 

If I may just make a suggestion now that I have you here.. (well 2 actually)

One will be the inclusion of this modpack : 

Farm Life v3
https://7daystodiemods.com/farm-life-v3-continuation-of-stasis-farm-life-mod/

It extend all the farming, food, etc, adding new trees, new plants and the ability to farm animals too.

And the second thing, is a thing that doesn't exist in any modpack I played so far.. Is a "End Boss". I don't know if its possible, but wouldn't it be great to have a final boss for the modpack that you can only beat once you have grinded all the bests equipment, armor and weapons? That gives a final objective for the modpack.

Anyways, thanks again for your quick response and update !!
