### ISSUE TITLE
HD BlunderBuss broken

### ISSUE THREAD

**Issue by razorboi** [War3zuk/War3zuk-Alpha-18-Stable-AIO#4]
So the BlunderBuss is one of my favorite weapons in 7DTD so when I saw a HD BlunderBuss with 2 rounds i was super hyped.

But currently the HD BlunderBuss does 0 damage even shows in the equipment description :(

**Comment by War3zuk** [comment]
Ummm Just loaded it up & it says 4 per pellet x10 = 40 Dmg per shot ? is it the AIO your using or a Modlet cos you havent said....

**Comment by War3zuk** [comment]
Checked the HD Guns & Ammo Modlet, Fixed & also I rebuilt the Spas 12 in the AIO so ive updated this Modlet to be the same, Default Spas 12 is now Black & when crafted doesnt have it Reflex sight, That like the Silencer is now crafted in the Gunbench once unlocked Via the HD Mods Schematic
