### ISSUE TITLE
Problem with new zombies

### ISSUE THREAD

**Issue by xBeathovenx** [War3zuk/War3zuk-Alpha-18-Stable-AIO#6]
Hi i got a problem with the added zombies.
When they fall to the ground they dont lay there stunned, they slide over the ground and attack.
Only happens with the game running on server, sp worked fine.

**Comment by War3zuk** [comment]
Thats the lag between server & player.. the fact it doesnt do it in SP
tells you that... alsi ragdoll has been disabled while i work on sorting
out a bug
