### ISSUE TITLE
I keep getting Localization error

### ISSUE THREAD

**Issue by Grimstout** [War3zuk/War3zuk-Alpha-18-Stable-AIO#7]
I have followed every protocol for installing this mod like any other mod for 7D2D. I had to put the Localization.txt file on the whitelist for Darkness Falls mod. I did the exact same thing here after having the same issue. That did not fix the problem for the error. Here is a pastebin for log. https://pastebin.com/Y8EhDSLH I have even tried installing after cloning my 7D2D game files and then putting your files for this mod into the folder. Any help would be appreciated.

**Comment by War3zuk** [comment]
Ive never had to do that & no one has ever mentioned this so I assume its something on your end cos you shouldnt need to add permissions for any localization files... Im not even sure why your having this issue.... not enough information...

**Comment by War3zuk** [comment]
Install the 7 days to die mod launcher...... make sure your steam install is clean of any modded file.... install & presync... as for a steam install its pretty much the same except your dragging the data & mods folder into your steam install

**Comment by Grimstout** [comment]
Yeah pastebin is all the information the log file is giving. I gave the file all the permissions and whitelisting it needs to function. I even turned off my antivirus to make sure.

As for the install. It cannot get any cleaner then a full wipe of reg and system of any 7D2D files before installing the game and mods again both ways.(Mod Launcher and 7D2D files cloned.) If I find a fix I will let you know. Thank you
